import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { MobileLayout } from '@/6_shared/ui/MobileLayout'
import localFont from 'next/font/local'
import { Toaster } from '@/6_shared/ui/sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2', // 폰트 파일 경로
  display: 'swap',
  weight: '100 900',
  variable: '--font-pretendard', // 3. Tailwind에서 쓸 변수명 지정
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body
        className={`${pretendard.className} ${geistMono.variable} antialiased`}
      >
        <MobileLayout>
          {children}
          <Toaster position="top-center" richColors />
        </MobileLayout>
      </body>
    </html>
  )
}
